name: "Test and Deploy"

on:
  workflow_run:
    workflows: ["Docker Publish"]
    types:
      - completed

env:
  TF_VAR_ACCESS_KEY: "${{secrets.TF_VAR_ACCESS_KEY}}"
  TF_VAR_SECRET_KEY: "${{secrets.TF_VAR_SECRET_KEY}}"


jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
        # default set of ruff rules with GitHub Annotations
        ruff --format=github --target-version=py37 .
    - name: Test with pytest
      run: |
        pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init -backend-config="access_key=${TF_VAR_ACCESS_KEY}" -backend-config="secret_key=${TF_VAR_SECRET_KEY}"

    - name: Terraform Plan
      run: terraform plan
